name       : kiconthemes
version    : 5.105.0
release    : 68
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.105/kiconthemes-5.105.0.tar.xz : 15178a35da23f78cbbac1a9d40554c9ed46f4426f7669f463260061f463f23bf
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.library
summary    : Icon GUI utilities.
description: |
    Icon GUI utilities.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - kconfig-devel
    - karchive-devel
    - kconfigwidgets-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
