name       : kiconthemes
version    : 5.78.0
release    : 47
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.78/kiconthemes-5.78.0.tar.xz : fb887e4d93cdd240545c8c16431cafafe3ec3c696589540d79a0e28b92084d6b
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.library
summary    : Icon GUI utilities.
description: |
    Icon GUI utilities.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - kconfig-devel
    - karchive-devel
    - kconfigwidgets-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
