name       : kiconthemes
version    : 5.44.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/kiconthemes-5.44.0.tar.xz : e4f31bde7daea7b748ac2b943ebf69c9b2eb27e5375d7c8cc9508cc1f16779f6
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Icon GUI utilities.
description: |
    Icon GUI utilities.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kauth-devel
    - kcodecs-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
