name       : kiconthemes
version    : 5.40.0
release    : 8
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.40/kiconthemes-5.40.0.tar.xz : 7d83b48411ebc177f8b998050b9d5ffd612c763275f1121a2470dded4a97de44
license    : LGPL-2.1
component  : desktop.library
summary    : Icon GUI utilities.
description: |
    Icon GUI utilities.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kauth-devel
    - kcodecs-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
