name       : kiconthemes
version    : 5.43.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.43/kiconthemes-5.43.0.tar.xz : 5ce7918311b89e30a4715f3ebeeb7263c550c9e9c59556a1a6e45ad24442ac80
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Icon GUI utilities.
description: |
    Icon GUI utilities.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kauth-devel
    - kcodecs-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
