name       : kiconthemes
version    : 5.61.0
release    : 30
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.61/kiconthemes-5.61.0.tar.xz : 341741abd0b8aeeec8a2a87fe781b4ec1ab593563b1c063cdfdccead3706cdd7
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Icon GUI utilities.
description: |
    Icon GUI utilities.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kauth-devel
    - kcodecs-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemviews-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
