name       : kiconthemes
version    : 5.67.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.67/kiconthemes-5.67.0.tar.xz : b8d48309efe3a5610483bad7d49ba9c30230e05c3db89b03aca0d2480fe43a5d
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Icon GUI utilities.
description: |
    Icon GUI utilities.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemviews-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
