name       : kiconthemes
version    : 5.80.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.80/kiconthemes-5.80.0.tar.xz : 92f2dc363fb8e6b7acdf1d7013d5b06f1f825466d8db00f79cd73cfc3ed9768c
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.library
summary    : Icon GUI utilities.
description: |
    Icon GUI utilities.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - kconfig-devel
    - karchive-devel
    - kconfigwidgets-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
