name       : kiconthemes
version    : 5.49.0
release    : 17
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.49/kiconthemes-5.49.0.tar.xz : 55b0708aaffb8e1d2e5dfede6a378a2f35386bf585e7294fadc08958b599f7b8
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Icon GUI utilities.
description: |
    Icon GUI utilities.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kauth-devel
    - kcodecs-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
