name       : kiconthemes
version    : 5.28.0
release    : 2
source     :
    - http://download.kde.org/stable/frameworks/5.28/kiconthemes-5.28.0.tar.xz : 0c2f9bb7639f2febc98a150be07a7b00953ac58b2faf1f11646c07ebb0beacc4
license    : LGPL-2.1
component  : desktop.library
summary    : Icon GUI utilities.
description: |
    Icon GUI utilities.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - karchive-devel
    - kauth-devel
    - kcodecs-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
