name       : kiconthemes
version    : 5.63.0
release    : 32
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.63/kiconthemes-5.63.0.tar.xz : dce004b5a210b7a96e78533909cb91ed2168534ae6303499f0777ac8c8b5e4a2
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Icon GUI utilities.
description: |
    Icon GUI utilities.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemviews-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
