name       : kiconthemes
version    : 5.65.0
release    : 34
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.65/kiconthemes-5.65.0.tar.xz : 6549774254705861654e0393ab53b7a06b62415644d6bbe5479f7458b22895c5
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Icon GUI utilities.
description: |
    Icon GUI utilities.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemviews-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
