name       : kiconthemes
version    : 5.74.0
release    : 42
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.74/kiconthemes-5.74.0.tar.xz : f51f0c75f50da3d119448f387c65fa69785c2c1bc82b61407bb92bf80cab31b5
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Icon GUI utilities.
description: |
    Icon GUI utilities.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemviews-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
