name       : kiconthemes
version    : 5.47.0
release    : 15
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.47/kiconthemes-5.47.0.tar.xz : b7e17d2ed46b31ae13d87397ae78717701d4f9515d1a647b52a6b14c5f684892
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Icon GUI utilities.
description: |
    Icon GUI utilities.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kauth-devel
    - kcodecs-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
