name       : kiconthemes
version    : 5.72.0
release    : 41
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.72/kiconthemes-5.72.0.tar.xz : 55e45a77ddea27fb0f0d130e2f568540443e04e454c1f1a7b746bef5a782f989
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Icon GUI utilities.
description: |
    Icon GUI utilities.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemviews-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
