name       : kiconthemes
version    : 5.25.0
release    : 1
source     :
    - http://download.kde.org/stable/frameworks/5.25/kiconthemes-5.25.0.tar.xz : dfea9b4da835c028b62faec6550d279a3a75874ff88d996d2b603be4f9b228b5
license    : LGPL-2.1
component  : desktop.library
summary    : Icon GUI utilities.
description: |
    Icon GUI utilities.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - kauth-devel
    - kcodecs-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
