name       : kiconthemes
version    : 5.38.0
release    : 6
source     :
    - https://download.kde.org/stable/frameworks/5.38/kiconthemes-5.38.0.tar.xz : 2a7dc525c1e9eea8c8952ca4eeccc22c28bb37ea83895fd7166174263218aa07
license    : LGPL-2.1
component  : desktop.library
summary    : Icon GUI utilities.
description: |
    Icon GUI utilities.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kauth-devel
    - kcodecs-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
