name       : kiconthemes
version    : 5.90.0
release    : 59
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.90/kiconthemes-5.90.0.tar.xz : 33f4cb7b18150cc4e54f1e3e0338c40ee0617c25921d9154d0c2fbe03b897c70
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.library
summary    : Icon GUI utilities.
description: |
    Icon GUI utilities.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - kconfig-devel
    - karchive-devel
    - kconfigwidgets-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
