name       : kiconthemes
version    : 5.39.0
release    : 7
source     :
    - https://download.kde.org/stable/frameworks/5.39/kiconthemes-5.39.0.tar.xz : 2edd03b3424fcc02d203ac8e3238c17436ccc951892bfcda498494ff871199cc
license    : LGPL-2.1
component  : desktop.library
summary    : Icon GUI utilities.
description: |
    Icon GUI utilities.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kauth-devel
    - kcodecs-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
