name       : kiconthemes
version    : 5.76.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.76/kiconthemes-5.76.0.tar.xz : 3b3c4ab8369061418677c840963cc868dcecc2a4e57f0c73448e16a46773c7d3
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.library
optimize   : lto
summary    : Icon GUI utilities.
description: |
    Icon GUI utilities.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kitemviews-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
